Repository elysium-suite/aeacus, pull requests merged in 2020-08, with the labels that each got.

#40 Replace userExists and userDetail with WinAPI implementation
  docs/checks.md
  docs/userproperties.md
  src/aeacus.go
  src/checks_windows.go
  src/configs.go
  src/crypto.go
  src/info_windows.go
  src/mitigate.go
  src/phocus_linux.go
  src/phocus_windows.go
  src/release_linux.go
  src/remote.go
  src/scoring.go
  src/utility.go
  src/utility_windows.go
  src/web.go
Labels: enhancement

#41 Improve documentation, error reporting, modularity
  README.md
  misc/id_linux.sh
  src/aeacus.go
  src/checks.go
  src/configs.go
  src/crypto.go
  src/crypto_test.go
  src/gui_linux.go
  src/gui_windows.go
  src/info_linux.go
  src/phocus.go
  src/phocus_linux.go
  src/phocus_windows.go
  src/release_linux.go
  src/remote.go
  src/routines.go
  src/scoring.go
  src/structs.go
  src/utility.go
  src/utility_linux.go
Labels: enhancement

#60 Added some magic posh to clear run history
  TODO.md
  src/release_windows.go
Labels: enhancement

#58 Implement debug log viewing, remote shell access
  README.md
  misc/install.sh
  src/aeacus.go
  src/checks.go
  src/checks_windows.go
  src/configs.go
  src/crypto.go
  src/release_linux.go
  src/release_windows.go
  src/remote.go
  src/routines.go
  src/scoring.go
  src/structs.go
  src/utility.go
  src/utility_linux.go
  src/utility_windows.go
  src/web.go
Labels: hax0r

#67 Teamid enhancements
  src/gui_windows.go
  src/release_windows.go
Labels: ui

#69 fix formatting
  .github/workflows/fmt.yml
Labels: ci, enhancement
